-- Warehouse + database + schema. XS warehouse keeps cost near zero for demos.

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS {{WAREHOUSE}}
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'realtime-market-stream ingest / query warehouse';

CREATE DATABASE IF NOT EXISTS {{DATABASE}}
  COMMENT = 'Medallion dual-write landing zone for realtime-market-stream';

CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.{{SCHEMA}};

GRANT USAGE ON WAREHOUSE {{WAREHOUSE}} TO ROLE {{ROLE}};
GRANT USAGE ON WAREHOUSE {{WAREHOUSE}} TO ROLE {{INGEST_ROLE}};
GRANT USAGE ON WAREHOUSE {{WAREHOUSE}} TO ROLE {{READER_ROLE}};

GRANT USAGE ON DATABASE {{DATABASE}} TO ROLE {{ROLE}};
GRANT USAGE ON DATABASE {{DATABASE}} TO ROLE {{INGEST_ROLE}};
GRANT USAGE ON DATABASE {{DATABASE}} TO ROLE {{READER_ROLE}};

GRANT USAGE ON SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{ROLE}};
GRANT USAGE ON SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{INGEST_ROLE}};
GRANT USAGE ON SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{READER_ROLE}};

GRANT CREATE TABLE, CREATE STAGE, CREATE PIPE, CREATE FILE FORMAT
  ON SCHEMA {{DATABASE}}.{{SCHEMA}} TO ROLE {{INGEST_ROLE}};
