-- Destination tables used by sinks/snowflake.py ConnectorSnowflakeChannel.
-- VARIANT payload keeps Bronze/Silver/Gold event shapes without schema lock-in.

USE ROLE {{INGEST_ROLE}};
USE WAREHOUSE {{WAREHOUSE}};
USE DATABASE {{DATABASE}};
USE SCHEMA {{SCHEMA}};

CREATE TABLE IF NOT EXISTS {{DATABASE}}.{{SCHEMA}}.{{TABLE_TICKS}} (
  EVENT_TYPE    VARCHAR,
  SYMBOL        VARCHAR,
  EVENT_DATE    VARCHAR,
  INGESTED_AT   VARCHAR,
  PAYLOAD       VARIANT,
  TICK_ID       VARCHAR,
  PRICE         FLOAT,
  SIZE          FLOAT,
  SIDE          VARCHAR,
  LOADED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CHANGE_TRACKING = TRUE
COMMENT = 'Trade / tick dual-write from Bronze and Silver processors';

CREATE TABLE IF NOT EXISTS {{DATABASE}}.{{SCHEMA}}.{{TABLE_BARS}} (
  EVENT_TYPE    VARCHAR,
  SYMBOL        VARCHAR,
  EVENT_DATE    VARCHAR,
  INGESTED_AT   VARCHAR,
  PAYLOAD       VARIANT,
  WINDOW_START  VARCHAR,
  WINDOW_END    VARCHAR,
  OPEN          FLOAT,
  HIGH          FLOAT,
  LOW           FLOAT,
  CLOSE         FLOAT,
  VOLUME        FLOAT,
  ANOMALY_SCORE FLOAT,
  LOADED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CHANGE_TRACKING = TRUE
COMMENT = 'OHLCV + Gold anomaly dual-write from Gold processor';

GRANT INSERT, SELECT ON TABLE {{DATABASE}}.{{SCHEMA}}.{{TABLE_TICKS}} TO ROLE {{INGEST_ROLE}};
GRANT INSERT, SELECT ON TABLE {{DATABASE}}.{{SCHEMA}}.{{TABLE_BARS}} TO ROLE {{INGEST_ROLE}};
GRANT SELECT ON TABLE {{DATABASE}}.{{SCHEMA}}.{{TABLE_TICKS}} TO ROLE {{READER_ROLE}};
GRANT SELECT ON TABLE {{DATABASE}}.{{SCHEMA}}.{{TABLE_BARS}} TO ROLE {{READER_ROLE}};
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE {{DATABASE}}.{{SCHEMA}}.{{TABLE_TICKS}} TO ROLE {{ROLE}};
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE {{DATABASE}}.{{SCHEMA}}.{{TABLE_BARS}} TO ROLE {{ROLE}};
